### ISSUE TITLE
Not able to boot new firmware

### ISSUE THREAD

**Issue by sana-shaikh-2010** [skrishnakanth/ESP32_FOTA_via_EC25-module#2]
Hi..
I am able to download binary firmware file from my http server into EC25 GSM module, it reads also  .But when OTA begins garbage data displaying on serial monitor  and EC25 shown +CME ERROR .

**Comment by skrishnakanth** [comment]
> Hi..
> I am able to download binary firmware file from my http server into EC25 GSM module, it reads also  .But when OTA begins garbage data displaying on serial monitor  and EC25 shown +CME ERROR .

Hi 

Sorry for the late reply , i did not notice it for a longer time !!

I would like to know exactly which step it  pops up with error code, which will help me to understand your problem .

**Comment by skrishnakanth** [comment]
Sorry buddy,
Closing the issue since there is no reply from the user !
